name: Python Test App

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build on ${{ matrix.vm-os }}
    runs-on: ${{ matrix.vm-os }}
    strategy:
      max-parallel: 4
      fail-fast: true
      matrix:
        vm-os: [windows-latest, ubuntu-latest]
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      shell: bash
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run
      shell: bash
      run: |
        python app.py
        python app.py
        python app.py
    - name: Done
      shell: bash
      run: |
        echo "Good Job!"
